### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by neutron666** [n30nl1ght/Pokemon-Notifier#1]
Hallo.

Ich schreibe das einfach mal hier nieder, weil ich finde das dies im PR von der Pokemon-Go Map nicht so richtig ist. Also bei der Installation gab es diverse Probleme:
1. MySQL Passwörter mit Sonderzeichen funktionieren nicht.
2. --webhook-api-key Schalter musste ich erst per PR für die Map pullen
3. database.sql muss man importieren, wird nicht erwähnt
4. Webhook und damit Domain wo der Bot laufen müssen über gültiges SSL Zertifikat verfügen
5. Undokumentierte Befehle /bern usw..was macht man damit? Gruppenchats ?

Ich weiß das dies dein Projekt ist und du das nirgendwo groß angekündigt hast, ich würde es aber gerne nutzen, sieht toll aus. Evtl. kann man das eine oder andere noch ausbügeln. Leider läuft das ganze bei mir jetzt immer noch nicht. Es funktioniert zwar soweit alles, Bot kommuniziert, nimmt Kommandos an etc aber ich bekomme keine Pokemon gemeldet, egal was ich mache. Pokemons sind auf der Notify list usw, aber er meldet einfach nichts, evtl. kannst du da helfen.

**Comment by Memurame** [comment]
Hei.
Danke und in Deutscher Sprache verstehe ich es besser ;-)
Ich werde es mir heute Abend anschauen was du da geschrieben hast.
Gebe dir dann bescheid, und cool möchtest du mein Script nutzen.

**Comment by neutron666** [comment]
Gerne wie gesagt. Ich kann dir auch gerne bei dem Englisch helfen, Deutsch sollte ja kein Thema sein, am besten in Dateien auslagern die Sprachgeschichten. Wünschenswert wäre wie gesagt auch noch Groupchat, damit quasi alle in einem Chat die noti's bekommen. Aber erst einmal würde ich das Teil gerne überhaupt zum Laufen bekommen, aktuell geht er nicht, also die noti's.

**Comment by azd2** [comment]
Ich nutze es bisher nicht, weil mir Pokeradar noch ausreicht. Finde aber zum Beispiel das mit den Stickern hier toll und wäre auch gern bereit zu helfen, z.B. bei der Korrektur der Nachrichten, wenn Du möchtest.
Mit dem, was Du undokumentierte Befehle nennst, wird festgelegt, wo du benachrichtigt werden möchtest. Wie es aussieht, geht derzeit Bern, Burgdorf, Oberburg und Langnau.

Ich bin kein Programmierer, dennoch...wenn ich mir den Code ansehe, sieht es so aus, als müsstest Du erstmal mit dem Bot in einem Chat sein und diesen dann mit "/start" starten, hast Du das mal versucht?
Achja und danach z.b. mit "/add Taubsi" ein Pokemon zufügen. Mit "/list" kannst Du gucken, was auf der Liste ist.

Je mehr ich sehe, desto besser gefällt mir das... Das hier wäre eine Lösung für mein Problem, das unterschiedliche Leute von mir über unterschiedliche Pokemon beanchrichtigt werden wollen. Ich glaube ich sehe mir das doch mal an :-)

**Comment by neutron666** [comment]
Also ich sagte ja, der Bot ansich läuft, ich bekomme ja auch gesagt für WAS ich alarmiert werde usw, die Kommunikation usw tut, aber es alarmiert eben nichts, ich hab parallel ja PokeAlarm laufen und sehe das noti's kommen, nur kommen die wieso auch immer entweder nicht beim Bot an oder aber was anderes geht nicht. Das WO, also Bern usw hab ich gesehen, da wird aber Cchat aufgerufen, das sieht mir aus wie chat id's, also eigentlich als wäre das die Gruppenchat Funktion die ich gerne hätte. Auf jeden Fall sollten wir hier mit helfen den Bot weiter zu bringen, gefällt mir auch total gut was ich da so sehe.

Ich sehe es doch richtig das der Bot quasi PokeAlarm ersetzt, oder ? Weil der Bot selber ja auf den Webhook hört usw, sprich es wird die Map und der Bot benötigt.

**Comment by neutron666** [comment]
Ich habe jetzt auch noch einmal geschaut, die Datenbank wird auch mit Daten gefüttert, die Pokemon mit Ihren IV's usw sind drin, die entsprechende chat id (meine) und was gemeldet werden soll stehen auch in der Datenbank, alles scheint zu funktionieren, nur passiert nichts..

**Comment by neutron666** [comment]
Sorry, wenn es nervt..also das Debug Log von der Map sagt folgendes:

 webhook][   DEBUG] Response timeout on webhook endpoint

Was ich nicht verstehe...der Endpoint ist da..

Runtergebrochen auf PHP, wenn ich das ganze mit PHP 5.5 der 5.6 laufen lasse, bekomme ich obigen response timeout, sonst geht alles, gehe ich runter auf PHP 5.4, kommt zwar der response timeout nicht mehr, aber der Bot geht gar nicht mehr...also ich bin ab diesem Punkt jetzt echt ratlos.

**Comment by Memurame** [comment]
Ich habe ein neuer Branch erstellt "develop" dort bin ich zurzeit an den Änderungen, wie auch der Mehrsprachigkeiten und so.
Das mit "/bern" habe ich wieder raus genommen.

Werde im späteren verlauf vom Abend mich noch hinter die anderen dinge setzen.

**Comment by Memurame** [comment]
@neutron666 Ok ich habe mal ein Update gemacht.
Kannst es mal testen, ansonsten können wir schauen.

ZU der PHP Version. Ich habe bei mit PHP7.0 im einsatz.
Das mal so als Info

Hast du mal kontrolliert ob du die Webhook URL vom Telegram auch gesetzt hast?
PAssiert irgend wass wenn du im Bot /start eingibst?

Natürlich darfst du auch mitarbeiten und z.B eine Englische Sprachdatei erstellen oder so ;-)
Fühl dich frei einen Pull Request zu stellen.
Ich kann ja dann immer noch entscheiden.

**Comment by neutron666** [comment]
PHP 7.0 ist ne gute Info, habe ich als einziges nicht probiert. Ja wie gesagt, er macht alles, nur keine notifications :) Ich werde jetzt mal develop testen und berichten. Ob PHP 7.0 für die Allgemeinheit so gut ist, weiß ich nicht, ist ja relativ frisch und neu und nicht jeder kriegt das einfach so installiert :)

**Comment by neutron666** [comment]
Wenn du mir noch Änderungsrechte gewährst, würde ich mal die Sprachdateien anpassen.

**Comment by Memurame** [comment]
@neutron666 Wenn du magst könntest du die Anleitung noch zusätzlich in englisch verfassen :-)
Mach doch erst mal einen Fork und dann Pull requests

**Comment by neutron666** [comment]
@n30nl1ght Kann man dich irgendwie live erreichen ? Hangouts, Telegram, sonst irgendwie ? Aktuell habe ich schon einiges versucht, aber auch mit PHP 7 will es einfach nicht, ich sehe auch diverse PHP Errors usw..wäre einfacher das mal live zu besprechen.

**Comment by Memurame** [comment]
@neutron666 Telegram ist gut.
Mein name dort ist n30nl1ght
