### ISSUE TITLE
Sticker optional machen

### ISSUE THREAD

**Issue by neutron666** [n30nl1ght/Pokemon-Notifier#34]
Ganz im Stil von "PokeAlarm" könnte man das versenden der Telegram Sticker optional machen. Ein paar Leute mit denen ich gesprochen hatte fanden diesen Bot hier wirklich super, aber die Grafiken im Chat sind Ihnen etwas zu viel. Um die Nutzerzahl zu steigern und einfach weil ich ein Freund von Optionen bin, könnte man das evtl. einbauen. Entweder per config.ini option oder per Kommando an den Bot.

**Comment by Memurame** [comment]
Ich würde sagen per Config.
Jedoch auf die Chats beschränkt, denn im Bot kommen die Sticker ja nun nicht mehr direkt.

**Comment by Memurame** [comment]
Erledigt ;-)
Und hoffen wir das die Map bald wieder funktioniert.
